language: node_js
sudo: false
node_js:
- 12.13.0
script:
- yarn run test
- yarn run build
notifications:
  slack:
    secure: boC42wRfZElNcpO95BHScYmHwGptKLG1ynH/lzTmN9TauFpSsC/hLWoeLtmzRkSH+k/qWFu8bzrpm/vr9HEoeHhFtHgrCL9HX8EL9grm0fsG3tH9qFUymNwq0kpBPjoOkXsTHJM+VaEOXn+TfYI6s+IA719Z0zxk4kkg02rg4O1EbvknoI+2R6pmUkpeZhVXGvysAMECda7VEtXYYJ6luU47Aj3Lo4D2U1EtprFQw0JeQvLEaHxzVvVyPfCv9rSKR0FhUj9lhlBPEKx8pg+rARcWmVRagkl7cqaHyBO3HYsmYyg2rLzxnQ8oqhHz2fG/yHvUssoiOh7YTkdSjcT7TQJDJADKhO8PfqCjprNbHxZ6/5z/9SMNCulV+UawUxXDDBnArR4zbwBaGZ9XlLV7CLyToWf9i+o7MCnYyukqVpVDftHcgX5IFXVhQ5hodHWssbZG209yF3DVONdHqUMkJah6FTMREXPoTf1avomMQpM6j29IlULg58CI9IzLw5+yuIAyO0cO0Sar1lLr3ro9tOTG1mrOPLEVZmAM8lQQX4Cg1Igx1YQZTXZYB97GdQgw4jYmdKZ450H2CdK2BYu0HcdYpJgH/SsFT+PqkCOq8CU6nogRjKS3WX0BI80NJIrii/FBBcwQQD4+PtCN9sYQ+iZFgeF1+sQ7g5XfazO/VBg=
    on_success: change
    on_failure: always
