name: test
on:
  push:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        node:
          - 14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - id: yarn-cache-dir
        run: echo "::set-output name=value::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.value }}
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test
